# These are supported funding model platforms

patreon: va_ll
USDT: 0x662DA8B0A573F510f57F73b09CcCE7f9749eA672
BTC: bc1qrnwtfl76wa9qgux4vtqu07lcdfynjatza64yvn
LTC: ltc1q0a4ysjddadlqxekh69mqlg560zx29t0jerknr8
TON: UQBwcy46nwQ3gtTOKczlDitNbfASzoxlbItL08IK_uNfVqNC
boosty: https://boosty.to/_vall_
DonationAlerts: https://donationalerts.com/r/va_ll_
Donate.Stream: https://donate.stream/va_ll
